title: My life
author: Zakir Syed 
email: zsyed1@ocdsb.ca
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  my life blah blah blah.

# social links
github_username: Zakir2006

show_excerpts: true # set to false to remove excerpts on the homepage
